services:

  db:
    image: mariadb:10.5
    container_name: whatsapp_db
    environment:
      MYSQL_ROOT_PASSWORD: jasindoRoot
      MYSQL_DATABASE: whatsapp_api
      MYSQL_USER: jasindo
      MYSQL_PASSWORD: jasindoR4153
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      
  api:
    image: ariutomo/whatsapp_jasindo_api:1.0
    container_name: whatsapp_jasindo_api
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - db
    restart: unless-stopped

volumes:
  db_data: